import { world, system } from "@minecraft/server"

system.runTimeout(() => {
    const globalProps = [
        { key: "balances", def: "{}" },
        { key: "tracked_items", def: "{}" },
        { key: "buyshop_items", def: "{}" },
        { key: "sellshop_items", def: "{}" },
        { key: "broadcasts", def: "{}" },
        { key: "tradeables", def: "[]" },
        { key: "chat_tags", def: "{}" },
        { key: "worldwarps", def: "{}" },
        { key: "mobs", def: "{}" },
        { key: "holograms", def: "{}" },
        { key: "leaderboards", def: "{}" },
        { key: "crates", def: "{}" },
        { key: "crateItems", def: "{}" },
        { key: "admin_claims", def: "[]" },
        { key: "banned_items", def: "{}" },
        { key: "banned_words", def: "{}" },
        { key: "bounties", def: "{}" },
        { key: "bounty_scoreboards", def: "[]" },
        { key: "spawners", def: "{}" },
        { key: "activespawners", def: "{}" },
        { key: "allowed_helper", def: "[]" },
        { key: "deadEntity_command", def: "{}" },
        { key: "attacker_command", def: "{}" },
        { key: "death_sound", def: "{}" },
        { key: "death_Particle", def: "{}" },
        { key: "redeem_codes", def: "{}" },
        { key: "builtInTags", def: true },
        { key: "menuCommands", def: true },
        { key: "menuItemCommands", def: true },
        { key: "oldinvsee", def: false },
        { key: "onlineside", def: true },
        { key: "protectedspawner", def: false },
        { key: "combatfly", def: false },
        { key: "itemclear", def: false },
        { key: "tpa", def: true },
        { key: "end", def: true },
        { key: "nether", def: true },
        { key: "economy", def: true },
        { key: "ctags", def: true },
        { key: "mtags", def: true },
        { key: "pmenu", def: true },
        { key: "landclaim", def: true },
        { key: "combatlog", def: true },
        { key: "cratetogle", def: true },
        { key: "rtp", def: false },
        { key: "worldBorderEnabled", def: false },
        { key: "itemNames", def: true },
        { key: "bountyToggle", def: false },
        { key: "mobCL", def: false },
        { key: "back", def: true },
        { key: "mobStack", def: false },
        { key: "wither", def: true },
        { key: "rtp_nether", def: true },
        { key: "rtp_end", def: true },
        { key: "headRank", def: true },
        { key: "visableHealth", def: true },
        { key: "ahModItems", def: false },
        { key: "bazaar", def: true },
        { key: "ah", def: true },
        { key: "proxchat", def: false },
        { key: "pv", def: false },
        { key: "dupekick", def: false },
        { key: "itemkick", def: false },
        { key: "cpskick", def: false },
        { key: "aurakick", def: false },
        { key: "wordkick", def: false },
        { key: "antiBundle", def: true },
        { key: "helper", def: true },
        { key: "dupe", def: false },
        { key: "inventory", def: false },
        { key: "echest", def: false },
        { key: "ban", def: false },
        { key: "freeze", def: false },
        { key: "mute", def: false },
        { key: "spy", def: false },
        { key: "itemban", def: false },
        { key: "manageclaims", def: false },
        { key: "vaults", def: false },
        { key: "adminClaim", def: false },
        { key: "warps", def: false },
        { key: "chatTags", def: false },
        { key: "trade", def: true },
        { key: "broadcast", def: false },
        { key: "mobSpawn", def: false },
        { key: "toggles", def: false },
        { key: "settings", def: false },
        { key: "customTagVisible", def: true },
        { key: "simple_spawners", def: false },
        { key: "playerheads", def: false },
        { key: "border", def: true },
        { key: "maintenance", def: false },
        { key: "minbounty", def: 1000 },
        { key: "crateTime", def: 3 },
        { key: "maxah", def: 10 },
        { key: "max_cps", def: 30 },
        { key: "pv_amount", def: 1 },
        { key: "maxspawnerstack", def: 256 },
        { key: "chatrange", def: 500 },
        { key: "mobStackRad", def: 4 },
        { key: "rtpAtt", def: 4 },
        { key: "worldBorder_overworld", def: 10000 },
        { key: "worldBorder_nether", def: 10000 },
        { key: "worldBorder_the_end", def: 10000 },
        { key: "rtpRad", def: 10000 },
        { key: "rtpCd", def: 300 },
        { key: "language", def: 1 },
        { key: "teleportTime", def: 10 },
        { key: "minflyheight", def: 5 },
        { key: "minflytime", def: 10 },
        { key: "reachdistance", def: 5},
        { key: "maxhomes", def: 3 },
        { key: "cleartime", def: 300 },
        { key: "cleardelay", def: 30 },
        { key: "combattime", def: 30 },
        { key: "minkillauradeg", def: 120 },
        { key: "maxland", def: 1000 }
    ];

    globalProps.forEach(prop => {
        if (world.getDynamicProperty(prop.key) === undefined) {
            world.setDynamicProperty(prop.key, prop.def);
        }
    });
}, 40);